components/Carbon.js
lib/constants.js
pages/editor.js

- Correctly set language when changed in the bar (before was hardcoded to JavaScript)
- Try and detect language if on `Auto` setting

Make language highlighting dynamic and handle auto selection

---

components/Carbon.js
lib/constants.js
package.json
pages/editor.js
yarn.lock

- fixes bug from merging #10 
- makes gist/drag-drop file content editable

Fixes edit bugs

---

README.md
components/Button.js
components/Header.js
components/Overlay.js
components/ReadFileDropContainer.js
components/style/Reset.js
package.json
pages/about.js
pages/editor.js

- Button component: div -> button
- File drop overlay
- Minor visual fixes

File drop overlay

---

handlers/twitter.js
lib/api.js
package.json
yarn.lock

- detect rate limiting on backend and respond accordingly
- notify the user when being rate limited

Add notification of Twitter rate limiting

---

pages/editor.js

Fix download button on Firefox

---

lib/constants.js

Add my favorite theme

---

lib/constants.js
lib/customModes/nimrod.js

Hey @dom96, I was able to find a custom Nim codemirror plugin that I think is working. I'm not too familiar with Nim though. Would you mind testing some examples with the language set to `Nim` at [this url](https://carbon-jesazyjrfd.now.sh/) and seeing if they highlight correctly?
references #27

Add Nim language

---

package.json
yarn.lock

Add repository info to package.json

---

components/ColorPicker.js
components/Page.js
components/style/Reset.js
components/style/Typography.js

Eventually, we'll want to make the whole site responsive but this should fix #31 for now.

Fix mobile overflow issue

---

README.md

Put actual link to blog post

---

lib/constants.js

Hey, guys!
Made me very sad that this project doesn't support Scala. So I made this little tiny patch.
I've checked `codemirror` and I ran the code on my machine. I'm a screenshot of [Fizz buzz](https://en.wikipedia.org/wiki/Fizz_buzz) implemented in Scala.
Hope it helps! Cheers!
P.s.: Yes, I've used `clike`, found example in [codemirror source](https://github.com/codemirror/CodeMirror/blob/282cf36664d05f776eba88a1f8ace03c1f085cd0/mode/meta.js#L122).
- Oto

Adding support for Scala.

---

components/Carbon.js
lib/constants.js

Fix solarized theme, remove redundant light:true

---

components/Carbon.js
lib/constants.js
pages/editor.js

- Support for C, C++, C#, Java, Scala
Closes #44 and closes #50

Add support for more clike languages

---

package.json
pages/editor.js
yarn.lock

Add prettier pre-commit hook

---

components/Button.js
components/ColorPicker.js
components/Dropdown.js
components/Settings.js
lib/constants.js

- Use CSS :hover selector
- Hover styles for Dropdown, ColorSelect, Button
Closes #84 and closes #83

Add button:hover styles

---

next.config.js

Looks like UglifyJs was the culprit. We should test this and make sure we're not disabling it in prod.

Fix slow page build

---

lib/constants.js

Closes #99.
For reference:
Cheers! ❤️

🎨 Add support for base-16 syntax

---

components/Button.js
components/Carbon.js
components/Meta.js
pages/editor.js

- Replace `Object.assign()` to spread operator
- Fix meta tag: `http-equiv` to `httpEquiv`

Use spread operator

---

components/Carbon.js
components/Settings.js
pages/editor.js

Adds ability to adjust window width.

Add width adjustment. (#91)

---

components/Carbon.js
components/Dropdown.js

Fix twitter jpg autoconversion

---

components/Carbon.js
components/ColorPicker.js
components/WindowControls.js
lib/util.js
pages/editor.js

Add color picker, alpha support

---

components/Carbon.js
components/Dropdown.js
components/Meta.js
components/Settings.js
components/Slider.js
components/ThemeSelect.js
components/Toggle.js
lib/constants.js
pages/editor.js

Pulls in fixes that were requested [here](https://github.com/dawnlabs/carbon/pull/89#issuecomment-333402486)

Fix component state issues

---

components/Carbon.js
lib/react-codemirror.js
lib/routing.js
package.json
pages/editor.js
yarn.lock

Also bumps react-codemirror -> react-codemirror2@3

Fix state bugs, fix drag-n-drop bugs, fix url encoding bugs

---

lib/constants.js

https://github.com/dawnlabs/carbon/blob/8dec652c2ab95708469499eb9027a9551092b765/lib/constants.js#L52-L68
```diff
- { 
-   id: 'solarized' 
- }, 
```
**Before**
**After**
Congrats on v1.0.0, BTW ❤️ 🎉

Remove erroneous constant

---

lib/constants.js

Fixes #128 
Prior to this PR, using Plain Text would crash the application.

Fix crash when using Plain Text

---

components/Carbon.js
pages/editor.js

Fixes background rendering problems
closes #130

fix background rendering

---

components/Carbon.js

Debounce language changes

---

components/Carbon.js

Add max-width to container

---

components/Carbon.js
pages/editor.js

Fix export alpha padding issue

---

components/Carbon.js
package.json
pages/editor.js
yarn.lock

Implement drag-n-drop image for backgrounds

---

lib/constants.js
lib/customModes/graphql.js
package.json
yarn.lock

Add GraphQL syntax. 
- Closes #38

GraphQL Type

---

lib/constants.js

Do not require opening PHP tag to highlight PHP code

---

components/BackgroundSelect.js
components/Button.js
components/Collapse.js
components/Dropdown.js
components/FontSelect.js
components/Settings.js
components/Toggle.js

- Remove 0.5px borders
- Fix bg-color-select element not fitting parent's width

Consistent borders

---

components/Footer.js
components/Header.js
components/Page.js

First accessability changes

---

package-lock.json
package.json
pages/_document.js
yarn.lock

Bump next.js, add _document

---

components/Footer.js
components/Settings.js

Vertical padding

---

components/Dropdown.js
components/FontSelect.js
lib/routing.js

Fix empty query param bug

---

LICENSE

Switch from 2017 to 2018 year in Licence text.

Update Licence year

---

lib/constants.js
lib/customModes/apache.js

Added the Apache language to the constants file and a new CodeMirror custom mode

Add syntax highlighting for Apache

---

README.md

Updated the README.md as asked. :smiley:

Added Sublime Text 3 plugin to README.md

---

pages/editor.js

set language to auto on file drop

---

README.md

I created vim plugin https://github.com/kristijanhusak/vim-carbon-now-sh .

Add link to vim plugin.

---

README.md

I created a simple Emacs plugin for Carbon.
Link to the repo: https://github.com/veelenga/carbon-now-sh.el

Emacs integration

---

README.md

Hello. I've added a note that Carbon can now be integrated into IntelliJ IDEA. Thanks for the awesome app!

IntelliJ IDEA integration

---

lib/routing.js

Added missing settings to mapping in routing.js so they will update the url

---

components/Carbon.js
components/WindowControls.js
pages/editor.js

Feature: Window Title

---

components/style/Font.js
lib/constants.js

Iosevka font

---

components/Dropdown.js
package.json
yarn.lock

Implement typeable dropdowns

---

server.js

setting up error code with res replaced by console.log

---

components/BackgroundSelect.js
components/Carbon.js
components/Dropdown.js
components/ExportSizeSelect.js
components/FontSelect.js
components/Footer.js
components/ImagePicker.js
components/RandomImage.js
components/Settings.js
components/Slider.js
components/ThemeSelect.js
components/Toggle.js
components/WindowControls.js
lib/routing.js
pages/editor.js

I ran the profiler before and after to improve rerender perf, especially related to keystroke updates.
I can upload the saved JSON profiler runs if anyone is interested 😄 
Here is a great article on the subject: https://medium.com/airbnb-engineering/recent-web-performance-fixes-on-airbnb-listing-pages-6cd8d93df6f4 (thanks @lencioni)

Performance improvements

---

package.json
yarn.lock

- https://zeit.co/blog/next5-1

Bump Next dependency

---

lib/constants.js

Add `stylus` so Gist in #294 works.
Closes #294

Fix issue 294

---

pages/editor.js

Fix Issue #137

---

components/Carbon.js
components/Editor.js
pages/index.js

Refactor index.js

---

components/style/Font.js
lib/constants.js

This patch adds the Fantasque Sans Mono font as an option.
The font is open source here,
https://github.com/belluzj/fantasque-sans

Add Fantasque Sans Mono font

---

components/Editor.js

Fix svg using Blob URLs

---

components/Editor.js
cypress/integration/gist.js
lib/api.js
pages/index.js

Use gist language response

---

components/Carbon.js
components/Editor.js
components/ImagePicker.js
handlers/twitter.js
lib/api.js
package.json
yarn.lock

add alt text support for Twitter images

---

components/Carbon.js
components/Editor.js
components/Slider.js
handlers/twitter.js
lib/api.js
lib/util.js
yarn.lock

- Fixes spinner 
- Runs prettier
- New yarn.lock

Fix spinner position

---

handlers/image.js

Update custom dom-to-image filter to match Editor

---

now.json
package.json

Move to now.json so GitHub integration kicks in

---

components/Carbon.js
components/Settings.js
components/Slider.js
lib/constants.js
lib/routing.js

Added line-height setting as per https://github.com/dawnlabs/carbon/issues/406.
While I was there, I also changed font-size so it increments by 0.5, since the steps were pretty big.

Adding line-height setting & granular font size.

---

components/Meta.js
lib/constants.js
lib/custom/themes/nord.css

This PR is to add Nord theme 
Based on [color palette Nord](https://github.com/arcticicestudio/nord) and [nord-visual-studio-code](https://github.com/arcticicestudio/nord-visual-studio-code)

Add Nord theme

---

README.md

Such a great project deserve a community, that's why I have added a badge.
It is a place where you can create threads for questions, announcements, features requests and more.

Community for carbon

---

components/Header.js
components/style/Reset.js

Begin responsiveness overhaul

---

components/Button.js
components/Editor.js
components/Meta.js
next.config.js
package.json
server.js
static/manifest.json
yarn.lock

- Adds web manifest
- Adds offline support w/ service worker
- Removes tweet button when offline
Closes #107

Implement PWA functionality

---

components/Carbon.js
components/Header.js
components/Meta.js
components/Page.js
components/style/Reset.js
components/style/Typography.js

This fixes the weird width/overflow issues on mobile
Closes #467

More Responsiveness Fixes

---

components/Settings.js
lib/util.js
package.json

Code split and load prettier dynamically

---

pages/about.js

I added a note into _About page_ for making images accessible at Twitter.
I didn't add my profile as a contributor, because it's only a small note (not source code involved).

Adding a note into About page for making images accessible at Twitter

---

components/Editor.js
pages/index.js

Move reset to prop of editor, and reset service-workers to prevent unable to reset cache issues in the future

move localStorage.clear() to prop of Editor

---

lib/constants.js

Add SPARQL language support

---

components/Meta.js
lib/constants.js
static/themes/one-light.css

Added atom one light theme ( = =
* JS:
* css: 
* markdown:

feat: add atom one-light theme

---

lib/constants.js

Add Turtle language support

---

lib/constants.js

- Add N-Triples language support

Add N-Triples language support

---

docs/README.zh_CN.md

Hi, I translate this readme doc to simplified Chinese

Add simplified Chinese translation

---

api/package.json
api/yarn.lock

Update version of puppeteer to address issues with emojis in the output.

Update puppeteer to latest version

---

api/Dockerfile
api/package.json
api/yarn.lock

upgrade puppeteer to 1.9.0

---

docs/README.es.md

Spanish translation for sharing the code snippet either via Twitter or saving the image file sounded very formal  in Spanish. So I used more colloquial language for the everyday users!

Updates way of sharing code snippet

---

components/ExportSizeSelect.js
components/FontSelect.js
components/ListSetting.js

Refactor list settings

---

components/Editor.js
components/Settings.js
package.json
pages/index.js

So many people asked for this, so we have decided to implement it! 🙂 
- Closes #561

Ability to name file downloads

---

components/Editor.js

This clones the editor node and does the encoding on that node in order to calculate the new width and height without mutating the original text.
- Closes #564

Fix Editor to use cloned element for calculating width

---

docs/README.es.md

with this pull request a style error is corrected that has the documentation in spanish, [ deesascapturas], this should be seen as three separate words,
[de esas capturas]

fix  misspelled

---

components/Settings.js

- Add some setting options back that were not meant to be removed.

add setting options back

---

package.json

- Adds linting to precommit hook

Add lint to precommit hook

---

components/Settings.js
components/Slider.js

- Keeps setting menu position fixed while sliders that change the editor width are being used.
Closes #600

Fix setting menu movement

---

components/Editor.js
components/ExportMenu.js
pages/index.js

Resolves #603 
- Prevents index page from updating
- Implements `shouldComponetUpdate` for `ExportMenu` to prevent unneeded updates caused by the `router` prop changing.
- Replaces `componentDidUpdate` with an `updateState` function in `Editor`

Reduce updates caused by typing

---

lib/constants.js

Adds the `TSX` language format for Typescript-based React projects. 
Fits in well with existing support for Typescript and JSX languages.

Add TSX language

---

.all-contributorsrc
docs/README.ta.md

* Added New **README.ta.md**
> Added Tamil translation for **README.md**
* **Use Tamil translation to Write Tamil**

added tamil translation

---

.travis.yml
cypress/integration/gist.js
package.json
yarn.lock

Run cypress tests against localhost

---

cypress/integration/basic.js

Add CLI integration test

---

.eslintrc.js
components/BackgroundSelect.js
components/Dropdown.js
components/Footer.js
components/ImagePicker.js
components/ListSetting.js
components/RandomImage.js
components/ThemeSelect.js
components/Themes.js
components/Toggle.js
package.json
yarn.lock

@raboid do you mind checking over this for visual/behavioral differences? I don't think there will be many if any.

Accessability improvements

---

components/Editor.js
package.json
yarn.lock

Remove react-dnd dependencies + use react-dropzone instead

---

next.config.js
now.json

Simplify next.config.js

---

components/Carbon.js
components/Editor.js
package.json
pages/embed.js
yarn.lock

@raboid thoughts on making this change? 
* remove resize-observer polyfill and use universally support mutation observer
* clean up <Carbon/> props

Remove resize-observer

---

components/RandomImage.js

As a side effect, this improves how/when the cache is refilled

Use hooks for RandomImage

---

components/ImagePicker.js
components/Meta.js

Move react crop stylesheet into component

---

components/Carbon.js
components/Editor.js
pages/embed.js

Do you think this is a good idea?

Use forward ref in carbon

---

components/ImagePicker.js
components/Meta.js

I think i finally have this working appropriately 😅

Preload stylesheets

---

components/Meta.js
cypress/integration/localStorage-spec.js
pages/index.js

This isn't needed if we go with https://github.com/dawnlabs/carbon/issues/663,
but is helpful w/o it

debounce updating query string and localStorage

---

.all-contributorsrc

add Farzad YZ to all contributors

Add Farzad YZ to all contributors

---

lib/constants.js

Twig is a supported language in CodeMirror ([twig example on the website](https://codemirror.net/mode/twig/index.html), [twig.js on Github](https://github.com/codemirror/CodeMirror/blob/master/mode/twig/twig.js)), so it would be awesome to get Twig support in Carbon as well!

Added Twig language support

---

.eslintrc.js
components/ApiContext.js
components/Editor.js
components/ImagePicker.js
components/RandomImage.js
components/TweetButton.js
lib/api.js
package.json
pages/index.js
yarn.lock

@raboid I have been wanting to make this change for awhile now. What do you think?

Read all api calls from context

---

components/Editor.js
components/ExportMenu.js
components/TweetButton.js
package.json
yarn.lock

Refactor disable PNG

---

next.config.js
pages/index.js

Only register service-work for editor

---

package.json
yarn.lock

Greenkeeper/@dawnlabs/tacklebox 0.0.10

---

README.md

I'm the author of CodeExpander, and I've added carbon features to the program that make it free and save carbon's watermarks. Here's what you can see:
Create and share beautiful Snippets：
Other features of the software:
- Unlimited public/private snippets
- Unlimited snippets group
- Cloud synchronization, online editing and sharing support
- Instant instruction support
- Dynamic script snippet support
- Custom date, simulated keyboard macros, generated text template support
- Code highlighting, formatting, substitution support
- Generate custom theme snippet images(png/svg)
- Search snippet support
- Proxy
- Cross-platform support
- Hot update support
...
If you like it, you can also experience it for free.

Add CodeExpander

---

lib/routing.js
pages/index.js

@raboid can you test with `highlights`? Does this refactor allow us to simplify any other `highlights` code?

Simplify routing code

---

components/Carbon.js
components/Editor.js
components/EditorContainer.js
components/ExportMenu.js
components/Input.js
components/Themes/ThemeCreate.js
components/Themes/index.js
lib/constants.js
pages/index.js

(as a bonus, made filename input an uncontrolled components)

Refactor themes settings

---

components/Carbon.js

After reading [this tweet](https://twitter.com/joelnet/status/1118566432193671168?s=12), I want to increase the watermark contrast a bit to make it more readable. Thoughts @jakedex?

Improve watermark contrast

---

components/ExportMenu.js

Update location origin for embeds

---

components/BackgroundSelect.js
components/ImagePicker.js
components/Input.js
components/Popout.js
components/RandomImage.js

A11y improvements

---

.travis.yml
components/BackgroundSelect.js
components/Button.js
components/Dropdown.js
components/ExportMenu.js
components/Themes/index.js
cypress/integration/visual-testing/button-test.spec.js
cypress/integration/visual-testing/syntax-test.spec.js
cypress/integration/visual-testing/theme-test.spec.js
cypress/plugins/index.js
cypress/support/index.js
cypress/util.js
package.json
yarn.lock

Hello!
At times maintaining separate visual test cases becomes a tiring task so using your existing examples setup we tried coming up with something that can ease this process. So I chose to use Cypress as the browser test harness, which Applitools has an SDK for. I started off with writing tests for some of the components so it's sort of a "smoke test" but you can add more if you'd like.
Visual regression involves comparing the pixels visually like a human would, ideally ignoring differences that a human couldn't perceive e.g. 1 pixel changes, differences in how browsers render images, drop shadows, etc. to avoid false positives; but you can still do a strict 1:1 pixel match if that's your preference.
Applitools thankfully  [provides an SDK](https://applitools.com/tutorials/cypress.html) …

Introducing Applitools

---

components/ExportMenu.js

Add keyboard listener for exporting

---

components/Editor.js

Fix Firefox open export

---

components/Editor.js

Only include transparent row on Twitter upload

---

package.json
pages/index.js
yarn.lock

Implement index error boundary

---

docs/README.ja.md

I've updated Japanese documents to follow original documents (from 2bf33aa to 1e5a173)

🇯🇵 Update Japanese documents to follow original documents

---

pages/embed.js

Send embed postmessage to top window

---

components/Editor.js

Closes https://github.com/dawnlabs/carbon/issues/564#issuecomment-512630653

fix encoding again

---

lib/constants.js

This PR adds XQuery as a language that carbon would now be compatible with. 
Made a small change to constants.js and added XQuery as a language that can be used.

Added: XQuery

---

components/BackgroundSelect.js
components/Carbon.js
components/ColorPicker.js
components/Editor.js
lib/constants.js
lib/highlight-languages.js
next.config.js
package.json
yarn.lock

Bundle size

---

README.md

@8thHalfHour how does this sound for updated instructions?
Closes https://github.com/carbon-app/carbon/issues/845

Update installing carbon for desktop

---

pages/about.js

Typo in about.js

---

.github/FUNDING.yml

Adding an Ethereum address per https://github.com/carbon-app/carbon/issues/853#issuecomment-526777956
Closes #853

Update FUNDING.yml with Ethereum address

---

docs/README.es.md

I made some grammar improves in the Spanish translation.

Spanish translation improved

---

docs/README.de.md

I only changed three words in the german README, because it wasn't valid german before.

Fix translation error

---

components/Settings.js

Remove use memo from settings

---

components/Editor.js
components/ExportMenu.js
components/Footer.js
components/Page.js
components/Toolbar.js
components/style/Reset.js
pages/about.js
pages/account.js
pages/snippets.js

* Make toolbar fit window on mobile
#506

Improve mobile UI

---

.all-contributorsrc
README.md
components/Carbon.js
docs/README.br.pt.md
docs/README.cn.zh.md
docs/README.de.md
docs/README.es.md
docs/README.fr.md
docs/README.hi.md
docs/README.ja.md
docs/README.kr.md
docs/README.ml.md
docs/README.ta.md
docs/README.tr.md
lib/routing.js
lib/util.js

Load selected lines from query params

---

README.md
docs/README.se.md

Added Swedish translation för README.md. Hope it helps :)

Add Swedish translation of README

---

.all-contributorsrc
README.md
docs/README.br.pt.md
docs/README.cn.zh.md
docs/README.de.md
docs/README.es.md
docs/README.fr.md
docs/README.hi.md
docs/README.ja.md
docs/README.kr.md
docs/README.ml.md
docs/README.ta.md
docs/README.tr.md

Added Blog link which is written about carbon. Thank you.

Added My self as Contributor

---

docs/README.se.md

Proofread by Swedish friend for further improvements :) Tack så mycket @matrulda :)

Suggest changes to Swedish README

---

components/Carbon.js
components/Settings.js
lib/constants.js
package.json
yarn.lock

Display whitespace

---

components/MenuButton.js
components/Settings.js

* Separate settings into three panels: Window, Editor, & Misc
* Move editor settings like "Hidden characters" and "Line numbers" in with font settings

RFC: restructure settings menu

---

components/Carbon.js
components/Editor.js
components/SelectionEditor.js

Closes #899 
https://carbon-git-selection-editor-improvements.carbon-app.now.sh/

Make selection editor less invasive

---

docs/README.es.md

README.es has been updated to match with the main README file.
| EDITOR PLUGINS | LICENSE/OTHERS |
| --- | --- |
| ![Screen Shot 2019-11-28 at 2 00 48 PM](https://user-images.githubusercontent.com/28733681/69831707-d1036680-11e7-11ea-89cc-57f777f1eaff.png) | ![Screen Shot 2019-11-28 at 2 01 04 PM](https://user-images.githubusercontent.com/28733681/69831710-d365c080-11e7-11ea-94d0-cebc8ddfc21a.png) |

README.es updated

---

docs/README.br.pt.md

Update readme as the english's header version

---

docs/README.fr.md

Minor typo fix for French documentation

---

docs/README.es.md

I made some grammar improvements and added the "translations" section.

grammar improvements

---

next.config.js

Once this deploys, @Gaojianli could you give it a try on your browser?
https://carbon-git-attempt-to-fix-ms-edge.carbon-app.now.sh/
Closes #928

Attempt to fix ms edge

---

package.json
yarn.lock

upgrade next to fix url errors

---

.all-contributorsrc
README.md
components/Editor.js
components/ExportMenu.js
docs/README.br.pt.md
docs/README.cn.zh.md
docs/README.de.md
docs/README.es.md
docs/README.fr.md
docs/README.hi.md
docs/README.ja.md
docs/README.kr.md
docs/README.ml.md
docs/README.ta.md
docs/README.tr.md

Added 'Clipboard' button in Export menu. 
Closes #921

PR for Enable copy image to clipboard export #921

---

components/Editor.js

Remove old unsplash photocredit if it is an exact match

---

components/Carbon.js
components/SelectionEditor.js

Closes https://github.com/carbon-app/carbon/issues/946

Fix text selection state

---

pages/account.js

Show `Sign Out` only for logged in users

---

.all-contributorsrc
README.md
components/style/Font.js
docs/README.br.pt.md
docs/README.cn.zh.md
docs/README.de.md
docs/README.es.md
docs/README.fr.md
docs/README.hi.md
docs/README.ja.md
docs/README.kr.md
docs/README.ml.md
docs/README.ta.md
docs/README.tr.md
lib/constants.js

Added the [JetBrains Mono](https://github.com/JetBrains/JetBrainsMono) font to the settings of the app.

Added JetBrains Mono font.

---

.github/workflows/validate.yml

Use node 12 on ci

---

components/Billing.js
components/CopyMenu.js
components/Editor.js
components/ExportMenu.js
components/ImagePicker.js
components/LoginButton.js
components/SnippetToolbar.js
components/TweetButton.js
components/style/Reset.js
pages/snippets.js

* New copy action menu
* Pull `flex` style to globals
* Use `…`s
Closes #960

New copy action menu

---

components/ExportMenu.js

Add quick export button next to the export menu

---

next.config.js
package.json
yarn.lock

Upgrade next offline to v5

---

components/Themes/index.js
lib/constants.js

https://carbon-git-issue-987.carbon-app.now.sh/?bg=rgba(171%2C%20184%2C%20195%2C%201)&t=dracula&wt=none&l=text%2Fx-php&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=%2524result%2520%253D%2520%2524object-%253Emethod(%2524param)%253B

Allow setting variable 2 and 3 in config

---

components/Editor.js
components/Input.js
components/SnippetToolbar.js
lib/constants.js
lib/util.js
pages/snippets.js

Snippets name input

---

README.md
docs/README.br.pt.md
docs/README.cn.zh.md
docs/README.de.md
docs/README.fr.md
docs/README.hi.md
docs/README.ja.md
docs/README.kr.md
docs/README.ml.md
docs/README.ta.md
docs/README.tr.md

Improve README docs

---

components/Billing.js
lib/api.js
lib/client.js
next.config.js
now.json

Test Next public env vars

---

lib/api.js
pages/[id].js
pages/embed/[id].js

Allow passing filename query param to get snippet

---

components/ThemeSelect.js
components/WindowControls.js
components/svg/Controls.js
components/svg/WindowThemes.js

Closes #508
Closes #1003
Thank you @spikespaz for starting this PR for me!

Boxy window theme

---

components/Carbon.js
components/SelectionEditor.js

Implement underline text as error

---

components/Themes/GlobalHighlights.js
components/Themes/index.js
pages/embed/index.js

Fix a11y dark embed

---

.all-contributorsrc
README.md
components/WindowControls.js
docs/README.br.pt.md
docs/README.cn.zh.md
docs/README.de.md
docs/README.es.md
docs/README.fr.md
docs/README.hi.md
docs/README.ja.md
docs/README.kr.md
docs/README.ml.md
docs/README.ta.md
docs/README.tr.md

Window title extends over boxy controls

---

components/CopyMenu.js
components/Editor.js

Read container width and height at copy time

---

components/EditorContainer.js
components/Settings.js
cypress/integration/basic.spec.js

Improve reset state

---

components/Editor.js

Use snippet name as filename

---

components/CopyMenu.js

Encode asterisks for medium embeds

---

components/style/Font.js
cypress/integration/gist.spec.js

Clean up Fonts.js

---

components/Editor.js
lib/dom-to-image.js

@qw-in here is an **un-tested** branch, if you wanted to work off it. 
We just need to test it against the issues you checked it against in your last PR to make sure there is no regressions 🙂 
Closes #1082

Local dom-to-image

---

components/Carbon.js
components/Editor.js
pages/embed/index.js

Delete code that once included a transparent row for Twitter

---

cypress/integration/background-color.spec.js

Attempt to fix integration tests

---

lib/dom-to-image.js

Clean up escapePercentSign

---

components/Toasts.js

Took the lazy developer route… thanks for the idea @qw-in 🙏 
Closes #1062

Move toasts to bottom right

---

docs/README.es.md

Fixed typo on line 77 : click > clic (proper translation in spanish)
Closes #

Fixed typo on line 77

---

README.md

this is the recommended method FOR sharing Carbon on your own website or blog

fix grammar typo in readme

---

.all-contributorsrc
README.md
docs/README.nl.md

README in Dutch! :netherlands:
I wasn't entirely sure where to add the Dutch document to the Translations table in the English README.md. Let me know if you're happy with this.

Dutch translation of README

---

docs/README.fr.md

[doc] fr typos

---

lib/dom-to-image.js

Remove promise delay

---

.all-contributorsrc
README.md
docs/README.tw.md

Added a new README version in Taiwanese language.

added Taiwanese version README

---

components/Meta.js
pages/embed/index.js

Thanks @Pradhvan for posting the issue!
Closes #1138

Fix issue 1138

---

components/CopyMenu.js
components/ExportMenu.js
pages/about.js

Improve keyboard shortcuts

---

.all-contributorsrc
README.md
docs/README.br.pt.md
docs/README.cn.zh.md
docs/README.de.md
docs/README.es.md
docs/README.fr.md
docs/README.hi.md
docs/README.in.md
docs/README.ja.md
docs/README.kr.md
docs/README.ml.md
docs/README.nl.md
docs/README.pl.md
docs/README.se.md
docs/README.ta.md
docs/README.tr.md
docs/README.tw.md
lib/api.js
package.json
yarn.lock

Fixes and closes issue #1169 
Switches Axios to Redaxios.
This seems like the correct way to go about changing as I was viewing commits on other repositories doing it the same way.

Switches Axios to Redaxios

---

.github/workflows/validate.yml

Attempt to fix CI

---

components/BackgroundSelect.js
components/ColorPicker.js
components/Themes/ThemeCreate.js
lib/util.js

Fix `react-color` bugs

---

cypress/integration/security.spec.js
next.config.js

Update wren referral link

---

.all-contributorsrc
README.md
docs/README.it.md

Added Italian translation for README.md
I created a translation of the Readme in Italian because I saw that it was missing

Add Italian README.it.md

---

docs/README.cn.zh.md
docs/README.es.md
docs/README.nl.md
docs/README.pl.md
docs/README.se.md
docs/README.tw.md

Just fix a dead link of fossa logo and modified to the same size as the English version.
Closes #

Fix dead links of fossa logo image in i18n readme

---

docs/README.in.md

word fixes

---

README.md

Hi! I created a slack integration for carbon! You can check it out [here](https://github.com/faisalsayed10/carbon-slack).

Add carbon's slackbot to the community section

---

components/Carbon.js
lib/custom/autoCloseBrackets.js

Auto close brackets

---

.all-contributorsrc

add danBamikiya as contributor

---

docs/README.es.md

Corrected a spelling error in the documentation in Spanish. For better compression.
Closes #1285

Mispelled word fixed on spanish doc

---

components/Editor.js
components/ExportMenu.js

Consolidate type and format into one param

---

package.json
yarn.lock

Upgrade Next.js to 12

---

README.md
docs/README.br.pt.md
docs/README.cn.zh.md
docs/README.de.md
docs/README.es.md
docs/README.fr.md
docs/README.he.md
docs/README.hi.md
docs/README.in.md
docs/README.it.md
docs/README.ja.md
docs/README.kr.md
docs/README.ml.md
docs/README.nl.md
docs/README.pl.md
docs/README.se.md
docs/README.ta.md
docs/README.tr.md
docs/README.tw.zh.md
docs/README.ua.md

changed the number of people who contributed to 160. already reached 160 people who contributed to this project.
https://github.com/carbon-app/carbon/graphs/contributors

update readme.md and all readme.md in the docs folder

---

yarn.lock

Upgrade codemirror-solidity

---

lib/custom/modes/riscv.js

Fix typo in riscv.js

---

docs/README.es.md

Fixes translation in paragraph 86 in spanish translation.
No break on code.
Closes no previous PR.

Fix translation (paragraph 86)

---

package.json
yarn.lock

chore: Upgrade next-pwa to latest

---

cypress/integration/security.spec.js
next.config.js

Fix issue 1347

---

components/Editor.js
components/EditorContainer.js
components/ShareMenu.js
components/SnippetToolbar.js
lib/constants.js
pages/about.js

Implement save button

---

components/Editor.js

Clear highlight state on theme selector change

---

components/Carbon.js
components/Editor.js
components/WindowControls.js
lib/routing.js

Implement titleBar query support

---

docs/README.es.md

This PR updates the Spanish documentation to match content of the current README.md.
Closes #

chore(docs): update README.es.md

---

docs/README.ta.md

Documentation changes only.
* Not sure who made the translation, but I am a native Tamil speaking person.
* Updated a few totally wrong translations.
I have been a power user of Carbon so this is going to be my first contribution.

Fixed the obvious transliteration typos.

---

lib/constants.js

It's a probabilistic programming language that is available in highlight.js.
Mainpage: https://mc-stan.org/
Github: https://github.com/stan-dev

add Stan language

---

README.md

add Arabic Readme file in translation table
Closes #

add link in translation table

---

docs/README.ru.md

Fixed typo in README.ru.md

---

.all-contributorsrc
docs/README.bn.md

- Translated Readme to Bengali

Add Bengali Translation

---

README.md
docs/README.bn.md
lib/dom-to-image.js

chore: fix some typos

---

README.md
docs/README.fa.md

This commit contains the up-to-date main README.md file, translated to farsi.
Please Also add the language "فارسی" to the docs languages.

Add Readme in Farsi
