package.json, pages/editor.js, yarn.lock
Version 1.0.0 has a debouncing issue where it doesn't rerender.
=> Rollback codemirror version 0.2.6

lib/constants.js
Adds F# and OCaml support by using CodeMirror's `mllike` mode - https://github.com/codemirror/CodeMirror/tree/master/mode/mllike
=> Add F# / OCaml mode

next.config.js, package.json, yarn.lock
Switch the temp strategy in `next.config.js` to use the production version of React from [here](https://github.com/zeit/next.js/issues/1195#issuecomment-326901737)
To avoid this 👇
=> Use production build of React

lib/constants.js, lib/customModes/kotlin.js
This adds Kotlin support to Carbon. Prior to this, `clike` was suggested for Kotlin.
| `kotlin`  | `clike` |
|---|---|
| ![carbon](https://user-images.githubusercontent.com/10191084/30944999-7064dc34-a3b0-11e7-9e38-6d65c0481ab4.png) | ![carbon 1](https://user-images.githubusercontent.com/10191084/30944993-6624ee3a-a3b0-11e7-920c-065df9c58a9e.png) |
=> Add Kotlin support

package.json
Unlike most, I don't use Bash on Windows, so running `yarn build` fails midway. This small PR makes it so you can have a single command without worrying about setting or using the environment variable properly for the platform.
Thanks :heart:
=> Add `cross-env` as a dev dependency

lib/constants.js
This adds `JSON` and `TypeScript` to this list of languages.
=> Add more JavaScript-like languages

README.md
**Problem**
On the [contribute section](https://github.com/dawnlabs/carbon#contribute), there is a instruction to start application, but this command is wrong. The correct is [`yarn dev`](https://github.com/dawnlabs/carbon/blob/master/package.json#L7).
**Solution**
Change `yarn start` to `yarn dev`.
=> Fix contribute section

pages/editor.js
Looks like https://github.com/dawnlabs/carbon/commit/0c365218d67508c992c080cde1ec293fbca0a953#diff-11a82058b621f771e497118318cf203fR75 introduced a tiny issue that Prettier didn't correct, so the CI is failing. A few open PR's already have this change, but in case those take a while to get merged in, this explicitly fixes it.
=> Fix failing CI

components/Carbon.js, components/Settings.js, pages/editor.js
closes #114 
Now users can choose if line numbers in code are wanted or not.
=> adding support to 'line numbers' settings

components/Carbon.js, lib/react-codemirror.js
Currently the cursor constantly jumps at the end everytime you press a key in the editor
My changes is supposed to prevent that
=> fix cursor jumping at the end after every editor update

components/Carbon.js
CC: @chrissimpkins
This removes a font with ligatures as the default, but lets people opt-in to it, since others have wanted that in the past: https://github.com/dawnlabs/carbon/issues/30
=> Make default font one without ligatures

lib/routing.js
This PR addresses an issue with boolean query parameters like window controls, line numbers, etc. They were not being parsed as booleans, so if they were set to `false` in the url, they were not being reflected properly in the rendering because `"false"` is truthy.
This PR updates the routing code to correctly parse those params to the appropriate values so they are reflected in the rendering.
=> Fix boolean params

lib/routing.js
We were running `encodeURI` on the whole query state which only encodes certain characters (like whitespace). `encodeURIComponent` is needed to completely encode all characters.
Fixes #229
=> Fix character encoding of editor text

components/Carbon.js, components/Meta.js
☝️ both are tested on localhost (Chrome v65.0)
the green line is the first frame captured.
speed up by delaying codemirror theme & highlightjs (big lib)
=> improve first meaningful paint on browser

.gitignore, components/Editor.js
For IDEs that allow you to open selected code in Carbon, they only pass the language and the code. To avoid losing your localStorage config, the settings should be merged in the following order:
1. DEFAULT
2. localStorage
3. urlParams
This ensures that all required config is present and that url params trump all.
=> fix issue #321 - load defaults, then localStorage, then url config

cypress/integration/gist.js, pages/index.js
For example http://carbon.now.sh/3208813b324d82a9ebd197e4b1c3bae8 would still not set the language property because `initialState` is `null`.
=> Use gist language response - fix when no queryparams are given

lib/constants.js
This PR adds the language support for sTeX/LaTeX.
The constant id for sTeX/LaTeX has been added which is supported in Codemirror.
This is how your latex code would look like in Carbon:
Thanks.
=> Added sTeX/LaTeX Language Support

components/Dropdown.js
Fixes #420 where the application crashes after selecting a dropdown item
and then pressing the up or down arrow keys.
The app would crash because the default highlighted index for the Dropdown was from `this.props.list` while the actual items being displayed were in `this.state.itemsToShow`.  When up/down was pressed this discrepancy would cause an error.
`this.userInputtedValue` also changed even on just clicking on an item rather than just manually typing the value.  Once the crash was fixed, this issue would mean the list would only show 1 item since it would think the user inputted the full word manually.
=> Fix crash on up/down press in Dropdown

.gitignore, components/Editor.js, components/Settings.js, lib/constants.js, lib/routing.js
I was using Carbon this week (great tool btw), and thought to myself that the user experience might be a bit better if the file names were timestamped, like how the native screen capture tool on macOS saves files as `Screen Shot 2018-07-13 at 1.47.37 AM` or how [MonoSnap](https://monosnap.com/welcome) saves files as `screencast 2018-07-12 14-24-21.mp4`
It's a minor improvement, but I personally find it easier to sort through multiple Carbon-generated files if they all have unique file names like this, since:
* Date/time is a lot easier to read through and gives more information than `carbon, carbon(1), carbon(2), etc.`.
* The order in which your files are displayed is consistent with time. If you instead save all files with the same name, you can get mixed up while deleting (e.g. if you …
=> Add optional timestamp to saved file names

handlers/image.js, lib/routing.js
The Base64 table has Char '+' [https://en.wikipedia.org/wiki/Base64](https://en.wikipedia.org/wiki/Base64), it will turn to blank characters in url request, It will cause some error when  deserializeState the state.
=> fix base64 bug

lib/custom/modes/nimrod.js
I changed the RegExp syntax to be more readable and improve maintanability
=> fixes #432, Nim's syntax highlighting is not weird anymore

components/Editor.js
add a button to the save menu called "copy", which opens the raw image data in the window so users
can directly copy it for easy pasting into a variety of apps
Closes #49
There is currently not browser support for copying actual images, so this seems to be a reasonable workaround. Any thoughts?
=> feat(save): add "copy" button

components/Editor.js
This encodes the strings before measuring the width of the export container (which prevents the image from being cut off)
Closes #463
=> encode text before reading the container width

components/Editor.js, components/Header.js, components/Meta.js, components/Settings.js, components/Slider.js, handlers/image.js, lib/routing.js, lib/util.js
Following the discussion issue on https://github.com/dawnlabs/carbon/issues/443
For now it's only a naive simple formatCode using prettier's standalone package. It only uses Babylon parser.
Plan for changes:
* Smart parser switch: If the language is *auto* it should use babylon as default parser. Based on the supported list of languages built-in to the prettier and the detected language on Carbon, it should switch the parser if required.
* Showing an alert/toast in case format can't be done (prettier can be tricky sometimes)
* Adding prettier's options available in the settings dropdown
* Do the formatting in a web worker in case the code is a bit long.
@mfix22 @briandennis
=> WIP: integration with prettier

lib/constants.js
While they use the same mode, OCaml is easy to miss.
I split the entries so that there is a F# entry and an OCaml entry.
Thanks! :sparkles:
=> Split F# and OCaml entries

components/Carbon.js, components/Editor.js
Carbon still manages internal language state, but will get reconstructed when parent's language state changes.
=> Remove gDSFP in Carbon

components/Editor.js, lib/routing.js, lib/shallow-equals.js, pages/index.js
Fixes https://github.com/zeit/next.js/issues/4994
`componentDidUpdate` is called for both props + state changes, `onEditorChange` only has to be called when the state is changed, so I added a shallow equals check to make sure it's only updated when the state really has been changed.
This solves the back button issue by removing the custom history API being used. Next.js needs to control the history as it puts some `state` into the history entry for when you're using the back button. Hence why you saw the error.
=> Don't use custom history API

.github/ISSUE_TEMPLATE.md, .github/tonic.yml
Updated the link pointing to the "Adding themes/languages" note:
```diff
- https://github.com/dawnlabs/carbon#a-note-on-adding-themeslanguages
+ https://github.com/dawnlabs/carbon/blob/master/.github/CONTRIBUTING.md#a-note-on-adding-themeslanguages
```
=> Updated link to "Adding themes/languages" note

components/Carbon.js, components/ExportMenu.js
Hi guys. :) `v3.6.0` introduced [some breaking changes to the CLI](https://github.com/mixn/carbon-now-cli/issues/39) I’m maintaining and trying to keep in sync (feature-wise).
I texted @mfix22 on Twitter about maybe adding some (non-changing) hooks for the CLI, so this doesn’t happen in the future any more. :)
I hereby added four `id`s for all the things the CLI accesses. Let me know if any changes are needed (maybe namespacing?)… :)
Thanks for being so responsive about this, hope to patch the CLI as soon as this is merged and deployed. :)
🙏
=> Adds CLI hooks (IDs) to certain elements

README.md, pages/about.js
* Adding more information in About page about the use of images with source code. This warning is motivated after talking to Juanjo Montiel, a blind developer, who finds it impossible to read the source code if it's within images. Furthermore, there are other visual disabilities for which text within images cannot be enlarged correctly. On the other hand, the source code cannot be copied. I find it interesting to raise awareness of it.
* Updating the section `Export/Sharing` in README.md with the same information.
=> Caution about the use of images in a post

next.config.js, now.json, package.json, static/manifest.json, yarn.lock
Chrome for macOS now supports installing PWAs for desktop. With this method, we can support desktop/offline use cases automatically. 
🤷‍♂️?
Example: https://carbon-ds98yypkc.now.sh/
=> Add offline support

components/Editor.js, components/ExportMenu.js, components/GistContainer.js, lib/routing.js, lib/util.js, pages/embed.js
This encodes the entire URI before writing to `window.location`, requiring that we then decode it when reading from the router. 
Closes https://github.com/dawnlabs/carbon/issues/705
=> Fix Medium embedding workflow

components/Meta.js, lib/constants.js, package.json, yarn.lock
I think that VSCode's theme is the most beautiful theme out there. I'm not sure why it's not replicated absolutely everywhere, so I tried to give it a shot here.
Carbon cannot replicate perfectly VSCode's theme because it lacks a few classes and most classes aren't well defined, overlapping stuff that should belong in a different class.
Here's the above snippet, but in VSCode.
Problems are the following : 
* Functions calls are yellow in VSCode. In Carbon, function calls are mixed with text, which is white in VSCode.
* Declarations are deep blue in VSCode. In Carbon, declarations are mixed with flow control, which is purple in VSCode, into another category named "keywords".
* Classes are green in VSCode. In Carbon, classes are mixed with variables, which are pale blue in VSCode.
Overall, …
=> Add VSCode's theme

README.md
We've added an integration with Carbon in our tool `nef` - you can read more about it [here](https://nef.bow-swift.io/docs/tutorials/first-steps-with-carbon/)
In a general way, `nef` is a CLI that lets you have compile-time verification of your documentation written as **Xcode Playground**. Now, from version [0.3.0](https://www.47deg.com/blog/nef-0-3-0-release/#carbon-integration-2) we have integrated Carbon, so you can write in **official Apple playgrounds**, and export the whole snippets with just one command.
We love Carbon, and we usually use it; this is the reason for this integration and the request for adding in the Carbon's tool list.
=> nef - integration with Carbon

components/Meta.js, components/Themes/index.js, lib/constants.js, static/themes/synthwave-84.css
- Extended `THEMES` to include optional `shadows` setting.
- Added SynthWave '84 theme. See https://github.com/robb0wen/synthwave-vscode
- Added optional text shadows to previews.
Thought it would be cool to add text-shadows to the previews. The theme SynthWave '84 looks best with shadows.
Below is the original VS Code theme.
=> Added SynthWave '84 theme + Text Shadows

lib/constants.js
This PR adds my [a11y-dark theme](https://github.com/ericwbailey/a11y-syntax-highlighting#a11y-dark). It is a syntax highlighting theme that uses all WCAG AAA compliant values for color contrast.
Thanks for considering it! Carbon's a really great app, and I'm excited to be able to contribute 🎉
=> Add a11y-dark theme

README.md
Repository: https://github.com/bow-swift/nef-plugin
This project provides an extension for Xcode to integrate some nef features directly in the IDE. Using the core of nef, you can export snippets from your code selection directly in Xcode.
**Note** I think it could replace the old [Xcode extension](https://github.com/StevenMagdy/CarboNow4Xcode), but I let you to consideration ;)
=> nef - Xcode Editor Extension

components/EditorContainer.js, components/LoginButton.js, components/Page.js
This adds the Login/Account button to the top of all pages, including the account and snippets page. This makes transitions between pages look more natural as the button doesn't suddenly disappear. In addition, it adds the previously missing ability to sign out on the account/snippets page, which might be useful if the user discovers they're using the wrong account.
|Before|After|
|------|-----|
|![image](https://user-images.githubusercontent.com/10191084/69664196-bc369f80-103c-11ea-9153-a663c5931b73.png)|![image](https://user-images.githubusercontent.com/10191084/69664169-ab862980-103c-11ea-9ea8-a434ac9a9ec7.png)|
=> Display login button on all pages

components/Editor.js, lib/constants.js
This pull request fixes the issue that when selecting other presets, the first preset remains highlighted with "not allowed" cursor event and cannot be selected.
Blue preset is clicked, but first grey preset is still highlighted and cannot be selected.
Preset selection fixed.
In presets file, selected is based on the value of property preset from the default settings object. All preset objects do not have this property but have id instead, since default settings has property preset, all the presets inherit the same property preset, which is why the first preset was always highlighted. Fixed by replacing key name preset to id in default settings.
=> Fixed first prefix always selected(hightlighted / cursor "not allowed")

README.md
Add a link to a Telegram bot which uses puppeteer to interact with the website and generate an image everytime it receives text wrapped in three backticks (```), as well as a gist URL.
Supports options for changing the overall appearance of the genrated image.
Also supports manually specifying a language as the first line of the code block.
This is how it looks:
=> Add @carbonshbot to community section on README.md

components/ColorPicker.js
When dragging color picker, it's not changed color instantly, so I refactor color picker makes it works.
=> refactor(color-picker): drag the pointer smoothly

pages/about.js
When `Contribute` header in the README file was changed by b6995ff to `Contribute & Support` the link on the [about page](https://carbon.now.sh/about) wasn't updated accordingly.
=> Fix broken link to the contributing guidelines on the about page

components/Editor.js
Closes #1064
This PR attempts to solve the highlighting issue described in #1064 without reintruducing any of the issues from #564. For that reason I have manually tested with the following snippets and left it as a fairly naive solution:
1. [Snippet from #1064](https://carbon.now.sh/?bg=rgba(171%2C%20184%2C%20195%2C%201)&t=one-dark&wt=none&l=text%2Fx-csrc&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=1x&wm=false&code=int%2520main()%2520%257B%250A%2509printf(%2522%252510d%255Cn%2522%252C%252012345)%253B%2520char%2520s%255B1%255D%253D%2522%2522%253B%250A%2509printf(%2522format%2520string%2520%2525s%2522%252C%2520s)%253B%250A%257D%250A)
1. [Snippet from #564](https://carbon.now.sh/?bg=rgba(171%2C%20184%2C%20195%2C%201)&t=o …
=> Preserve syntax highlighting when exporting png that contains %XX

components/style/Font.js
According to #1044 issue, IBM Plex Mono won't loaded properly in Safari web browser. I remove some attributes when load font with `@font-face` and now it's loaded properly.
Before
After
Fixes #1044
=> Fix IBM Plex Mono font is missing in Safari

lib/dom-to-image.js
This is a quick fix for the backgrounds breaking - guess I'll have to spend more time with this whole encoding issue than initially anticipated. Really hoping to find some time to put together those tests but it's been sunny here :sweat_smile: 
Escaping the `%` sign was breaking some of the styles, specifically percentage units. But only for SVG :cry: 
Closes #1095
=> Fix encoding % sign breaking SVG background

components/Carbon.js
The option would be ignored when exporting the project through `next build && next export`, failing to hide the vertical scroller.
(Additional changes were presumable made automatically by the linter.)
=> Fix typo in scrollbarStyle option

lib/constants.js
Updated base16-light operator color to black (#000) instead of white (#fff)
Closes #1121
=> Updated base16-light operator color to black

README.md
Previous image was broken. Appears to have been deleted by Fossa as part of new brand guidelines: https://fossa.com/brand
Closes #1145
=> Fix sponsors

components/ShareMenu.js
when tweet and imgur buttons were merged in #1158 to ShareMenu component, tags were copied and pasted from the ExportMenu component. duplicate id tags were causing integration tests to fail. id and other tags updated to correspond to "share" rather than "export"
notes: there are no integration tests for the new ShareMenu component. also, the integration test for downloading images is failing and outdated, although it is skipped and not a part of CI so low priority
Closes #1171
=> share menu tags fixed

components/style/Font.js
As @vtmx points out in #1181, Carbon is sourcing a pretty old version of the Fira Code font. This commit uses the `@latest` version. Also, changes cdn from rawgit (which is discontinued) to jsDelivr.
Closes #1181
=> Fira Code Font - Set to latest version, switch CDN

components/style/Font.js
Changes @font-face definition of IBM Plex Mono from "Medium Italic" to "Regular."
- "Regular" rather than "Medium" to align with all other font definitions
- Users can still create italic screenshots by highlighting their code and clicking the italic button
Closes #1177
=> IBM Plex Mono (Medium Italic -> Regular)

lib/api.js
Reverts the changes of commit 520e19ab44065622a7a47c22d60ccd70de0e68bc. Setting changes to default values are no longer removed from the Firebase payload, avoiding the bug described in #1183. Passes E2E tests but I don't have a means to test Firebase network requests locally - @mfix22 can you share a deployment link, or test yourself if that's easier.
Closes #1183, although another change is required on backend to avoid storing default values.
=> Don't sanitize payload for storage

package.json, yarn.lock
For those who are building the site under Apple M1, sharp would be not able to install correctly and the building will be failed.
According to https://github.com/lovell/sharp/issues/2460 , upgrade to sharp v0.28.0 will solve the problem.
=> Upgrade sharp for solving the build failed under Apple M1

lib/constants.js
CodeMirror's `mllike` mode has sub-support for F# if provided the `text/x-fsharp` MIME type, so I've done so here.
I found this at CodeMirror's documentation for the `mllike` mode [here](https://codemirror.net/mode/mllike/index.html).
Before:
After:
=> Add separate language mode for F#

components/CopyMenu.js, components/Editor.js, components/ExportMenu.js, components/Page.js, components/Popout.js, components/ShareMenu.js
=> Responsive for mobile

components/Carbon.js
The code should not overflow on mobile when using the largest font size.
Detail: https://github.com/carbon-app/carbon/issues/1287#issuecomment-1032739971
- Editor -> Setting Max Size
- Window -> Setting Max Padding Horizontal Size
Closes #1287
=> Fix: Responsive design at the largest font size

pages/account.js
As stated in #1336, embedding saved snippets is part of the Free tier, but on the account page it is listed as part of the Diamand tier.
This MR fixes that.
=> Change account.js to reflect embeds are free

lib/api.js
=> chore: fix rate limit message typo

components/Editor.js
when exporting on safari, the image is offset to the left by 50%.
I adjusted the transform configuration to counter that position offset *ONLY* when `Safari` is detected in the user agent.
tested to work on the various resolutions (1x, 2x, 4x) for "download" and "open"
before:
After:
Closes #1351
=> [BugFix] Fix exported image cut off - Safari

lib/constants.js
This PR adds support for [Nix](https://nixos.org) to Carbon. On several occasions I've wanted to use Carbon for snippets of Nix code but have needed to use JavaScript or Ruby instead, which kinda works but doesn't look awesome. As Nix is already supported by Highlight.js, it seemed worth a try PRing support.
=> Add support for Nix

lib/constants.js
I started to work a lot with Cassandra Query Language recently and I'm constantly building examples and documentations using Carbon, but I realized that is a good thing to enable it by default since [CodeMirror](https://github.dev/codemirror/codemirror5/blob/9974ded36bf01746eb2a00926916fef834d3d0d0/mode/sql/sql.js#L382-L383) already have it setup by default.
* Enabled Cassandra Query Language (CQL) support.
=> feat: Adding Cassandra Query Language

components/Editor.js
**Issue:**  Image cutoff breaks Chrome, Brave on Mac and older Safari
**Solution:** Fix the position of generated image
Safari - 16.3
Brave -  v1.52.130
Chrome - 114.0.5735.198
Firefox - 115.0.2 
Closes #1474
=> fix: generated image position

components/ImagePicker.js, lib/custom/modes/riscv.js
=> chore: fix some typos in comments
